### PR TITLE
fix compilation with latest V and vfmt tvintris.v

### PR DESCRIPTION
**Pull request by spytheman**
This PR contains the following fixes:

* time.sleep_ms(x) => time.sleep(x * time.millisecond)
* consts were snake_cased
* v fmt -w tvintris.v
* unused variables / module imports were removed

The result is that now tvintris.v compiles without warnings/errors
with latest V 0.2.2 1178427 .

### CODE REVIEW

**Comment by nsauzede** [comment]
thanks
let me have a look

**Comment by nsauzede** [comment]
@spytheman I just checked your branch, which seems to build fine with latest V (thanks) but it looks like the `right-arrow` does not work ?
ie: the player on the right side, can move `left` but not `right` with the keyboard ?
can you confirm that ?

**Comment by spytheman** [comment]
it should be ok now

**Comment by nsauzede** [comment]
> it should be ok now

indeed !
thanks a lot ! LGTM

**Pull request merged**
